POST http://localhost:3000/project
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcnRoYWsucmF3YXRAc3R1ZGVudHMuaWlpdC5hYy5pbiIsIm5hbWUiOiJzYXJ0aGFrIHJhd2F0IiwiaWF0IjoxNjM2ODE2ODU4fQ.mD42iTOqnSQ4FeavikkQeCraxP24o5Wt5RU3t3JWv3A

{
    "name": "project1",
    "description": "Project 1 desc",
    "organisation": "Serc",
    "URL": "www.serc.in"
}

###

GET http://localhost:3000/project/619fd08d528a3635a7f54a6b/info
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTlmYjFiOGI0NTQ1ZDBjZGVkOGE1NmIiLCJlbWFpbCI6InNhcnRoYWtAZ21haWwuY29tIiwibmFtZSI6InNhcnRoYWsgcmF3YXQiLCJpYXQiOjE2Mzc4NjY3Mzd9.347P6BR-MgwOeNTVEuyUsKhYO8J0NHzqKqDPkZHK_V8

###

POST http://localhost:3000/project/task/619fd08d528a3635a7f54a6b
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcnRoYWsucmF3YXRAc3R1ZGVudHMuaWlpdC5hYy5pbiIsIm5hbWUiOiJzYXJ0aGFrIHJhd2F0IiwiaWF0IjoxNjM2ODE2ODU4fQ.mD42iTOqnSQ4FeavikkQeCraxP24o5Wt5RU3t3JWv3A

{
    "name": "task1",
    "URL": "www.exam.com",
    "description": "asd"
}