POST http://localhost:3000/project
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcnRoYWsucmF3YXRAc3R1ZGVudHMuaWlpdC5hYy5pbiIsIm5hbWUiOiJzYXJ0aGFrIHJhd2F0IiwiaWF0IjoxNjM2ODE2ODU4fQ.mD42iTOqnSQ4FeavikkQeCraxP24o5Wt5RU3t3JWv3A

{
    "name": "project1",
    "description": "Project 1 desc",
    "organisation": "Serc",
    "URL": "www.serc.in"
}

###

GET http://localhost:3000/project/tasks/:

###

POST http://localhost:3000/project/task/: