GET http://localhost:3000/test/61a1260f282df323112b263f
Content-Type: application/json
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhcnRoYWsucmF3YXRAc3R1ZGVudHMuaWlpdC5hYy5pbiIsIm5hbWUiOiJzYXJ0aGFrIHJhd2F0IiwiaWF0IjoxNjM2ODE2ODU4fQ.mD42iTOqnSQ4FeavikkQeCraxP24o5Wt5RU3t3JWv3A

###

61a1260f282df323112b263f